name: Build AdGuard DNS filter

on:
  push:
  schedule:
    - cron: '0 */6 * * *' # Every 6th hour

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: yarn
        run: |
          yarn install
          yarn run build
      - name: prepare deploy
        run: |
          mkdir build
          cp -rf Filters build/
        env:
          CI: true
