name: Build the filter

on:
  schedule:
    - cron: '30 0 * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: yarn
        run: |
          yarn install
          yarn run build
      - name: prepare deploy
        run: |
          mkdir build
          cp -rf Filters build/
        env:
          CI: true
