# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0/10 * * * *' # Every 30 minutes

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      
jobs:
  runscript:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Update backups
        run:  bash ${PWD}/backup/start.sh
